name: "Pull Request clean-up"

on:
  pull_request:
    types: [unlabeled, closed]

permissions: write-all

jobs:
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Slug action
        uses: rlespinasse/github-slug-action@v3.x

      - name: Init STAGE variable
        run: echo "STAGE=pr-${{ github.event.number }}-${{ env.GITHUB_HEAD_REF_SLUG }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm ci

      - name: Destory Stack
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'destroy'
          cdk_args: '--force'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STAGE: ${{ env.STAGE }}
